# Generated by Django 2.2.3 on 2019-07-01 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bairros', '0001_initial'),
        ('cidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelBlackListRua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('A', 'ATIVO'), ('R', 'RESOLVIDO')], default='A', max_length=100)),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('alteracao', models.DateTimeField(auto_now=True)),
                ('bairro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bairros.ModelBairro')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cidades.ModelCidade')),
            ],
            options={
                'verbose_name': 'Blacklist Rua',
                'verbose_name_plural': 'Blacklist: Ruas',
                'db_table': 'blacklist_rua',
            },
        ),
    ]
