# Generated by Django 2.2.3 on 2019-07-25 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cidades', '0003_auto_20190715_1145'),
        ('bairros', '0008_auto_20190718_1759'),
        ('blacklist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelBlackList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(blank=True, max_length=100, null=True)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('bounds_northeast_lat', models.FloatField(blank=True, null=True)),
                ('bounds_northeast_lng', models.FloatField(blank=True, null=True)),
                ('bounds_southwest_lat', models.FloatField(blank=True, null=True)),
                ('bounds_southwest_lng', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('A', 'ATIVO'), ('R', 'RESOLVIDO')], default='A', max_length=100)),
                ('usuario_atualizacao', models.CharField(default='Thomas Shelby', max_length=100)),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('alteracao', models.DateTimeField(auto_now=True)),
                ('bairro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bairros.ModelBairro')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cidades.ModelCidade')),
            ],
            options={
                'db_table': 'blacklist',
                'verbose_name': 'Blacklist',
                'verbose_name_plural': 'Blacklists',
            },
        ),
        migrations.DeleteModel(
            name='ModelBlackListRua',
        ),
    ]
