# Generated by Django 2.2.3 on 2019-08-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blacklist', '0002_auto_20190725_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelblacklist',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='modelblacklist',
            name='rua',
        ),
        migrations.AlterField(
            model_name='modelblacklist',
            name='bairro',
            field=models.CharField(max_length=250),
        ),
    ]
