# Generated by Django 2.2.3 on 2019-08-19 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blacklist', '0003_auto_20190813_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelblacklist',
            name='endereco_completo',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
