# Generated by Django 2.2.3 on 2019-08-22 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blacklist', '0004_modelblacklist_endereco_completo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelblacklist',
            old_name='usuario_atualizacao',
            new_name='usuario',
        ),
    ]
