# Generated by Django 2.2.3 on 2019-07-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelCidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('bounds_northeast_lat', models.FloatField()),
                ('bounds_northeast_lng', models.FloatField()),
                ('bounds_southwest_lat', models.FloatField()),
                ('bounds_southwest_lng', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('distancia_maxima_km', models.IntegerField()),
                ('endereco', models.CharField(blank=True, max_length=200, null=True)),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('alteracao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Informação da cidade',
                'verbose_name_plural': 'Informações das cidades',
                'db_table': 'cidades',
            },
        ),
    ]
