# Generated by Django 2.2.3 on 2019-07-12 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidades', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelcidade',
            name='distancia_maxima_km',
        ),
        migrations.AddField(
            model_name='modelcidade',
            name='distancia_maxima',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
