# Generated by Django 2.2.3 on 2019-07-06 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bairros', '0002_auto_20190706_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelbairro',
            name='distancia_maxima_km',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
    ]
