# Generated by Django 2.2.3 on 2019-07-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bairros', '0003_auto_20190706_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelbairro',
            name='distancia_maxima_km',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
