# Generated by Django 2.2.3 on 2019-07-12 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bairros', '0005_auto_20190712_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelbairro',
            name='distancia_maxima',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
