# Generated by Django 2.2.3 on 2019-07-18 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bairros', '0007_auto_20190718_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelbairroauxiliar',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cidades.ModelCidade'),
        ),
    ]
