# Generated by Django 2.2.3 on 2019-08-22 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bairros', '0009_auto_20190807_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelbairroauxiliar',
            old_name='nome_errado',
            new_name='nome',
        ),
    ]
